package love.forte.tools.enumcollection.examples.ksp

public fun main(): Unit {
    // `PermissionEnumSet` / `PermissionEnumMap` are generated by kotlin-enum-collection-ksp.

    val set = PermissionEnumSet(Permission.READ, Permission.WRITE)
    check(set.contains(Permission.READ))
    check(set.containsAny(listOf(Permission.EXECUTE, Permission.READ)))

    val mutableSet = set.mutable()
    mutableSet.add(Permission.EXECUTE)
    val immutableSet = mutableSet.immutable()

    println("Generated EnumSet: $set -> mutable=$mutableSet -> immutable=$immutableSet")

    val map = PermissionEnumMap(Permission.READ to 1, Permission.WRITE to 2)
    check(map[Permission.READ] == 1)

    val mutableMap = map.mutable()
    mutableMap[Permission.EXECUTE] = 3

    val immutableMap = mutableMap.immutable()
    check(immutableMap[Permission.EXECUTE] == 3)

    println("Generated EnumMap: $map -> mutable=$mutableMap -> immutable=$immutableMap")
}
